matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
language: java
sudo: false
git:
  depth: 1
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.m2"
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - openjdk11
before_deploy:
  - ./gradlew shadowJar
  - mkdir -p deploy
  - mv build/libs/*-bundled.jar deploy/$APPNAME-$TRAVIS_TAG-$TRAVIS_OS_NAME.jar
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: deploy/*
  file_glob: true
  on:
    tags: true
